# Generated by Django 5.0.1 on 2024-01-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
